name: Anilist Metrics
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # atualiza 1x por dia

jobs:
  anilist:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/anilist-favorites.svg
          token: NOT_NEEDED
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: Satirico
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, characters
          plugin_anilist_limit: 3
          plugin_anilist_limit_characters: 18